/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Macronutrients = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'protein' : IDL.Nat,
});
export const DailyGoals = IDL.Record({
  'calories' : IDL.Nat,
  'macros' : Macronutrients,
  'waterGoal' : IDL.Nat,
});
export const Meal = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'protein' : IDL.Nat,
});
export const GymSession = IDL.Record({
  'exercises' : IDL.Vec(IDL.Text),
  'durationMinutes' : IDL.Nat,
  'caloriesBurned' : IDL.Nat,
});
export const DailyLog = IDL.Record({
  'meals' : IDL.Vec(Meal),
  'waterIntake' : IDL.Nat,
  'date' : IDL.Text,
  'gymSession' : IDL.Opt(GymSession),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyGoals' : IDL.Func([], [DailyGoals], ['query']),
  'getDailySummary' : IDL.Func([IDL.Text], [DailyLog], ['query']),
  'getGymStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserHistory' : IDL.Func([IDL.Principal], [IDL.Vec(DailyLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logGymSession' : IDL.Func([GymSession, IDL.Text], [], []),
  'logMeal' : IDL.Func([Meal, IDL.Text], [], []),
  'logWaterIntake' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyGoals' : IDL.Func([DailyGoals], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Macronutrients = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  const DailyGoals = IDL.Record({
    'calories' : IDL.Nat,
    'macros' : Macronutrients,
    'waterGoal' : IDL.Nat,
  });
  const Meal = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const GymSession = IDL.Record({
    'exercises' : IDL.Vec(IDL.Text),
    'durationMinutes' : IDL.Nat,
    'caloriesBurned' : IDL.Nat,
  });
  const DailyLog = IDL.Record({
    'meals' : IDL.Vec(Meal),
    'waterIntake' : IDL.Nat,
    'date' : IDL.Text,
    'gymSession' : IDL.Opt(GymSession),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyGoals' : IDL.Func([], [DailyGoals], ['query']),
    'getDailySummary' : IDL.Func([IDL.Text], [DailyLog], ['query']),
    'getGymStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyLog)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logGymSession' : IDL.Func([GymSession, IDL.Text], [], []),
    'logMeal' : IDL.Func([Meal, IDL.Text], [], []),
    'logWaterIntake' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyGoals' : IDL.Func([DailyGoals], [], []),
  });
};

export const init = ({ IDL }) => { return []; };